### ISSUE TITLE
what about RedM natives? 

### ISSUE THREAD

**Issue by Roms1383** [ZOTTCE/fivem-wasm#5]
Hello! I open this new issue as a separate discussion thread about RedM natives : is this possible to allow for their support with this crate? I would actually be interested in slowly developing higher level traits and features based on the natives.

**Comment by Roms1383** [comment]
also please apologize if oftentimes I ask lame or noob questions because I'm not familiar at all with fivem ecosystem 😅

**Comment by zottce** [comment]
I haven't built RedM (they also support gta4 too?). I think there will be no difficulties to expand a natives generator with them.
It's defined [here](https://github.com/citizenfx/fivem/blob/master/ext/natives/codegen.lua#L559-L577)

**Comment by Roms1383** [comment]
would you mind opening [Github discussion feature](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository) so that we can keep carrying the discussion on various topics without bloating your Github repo issues ?

**Comment by Roms1383** [comment]
I have some ideas that I would like to share :)

**Comment by zottce** [comment]
done

**Comment by Roms1383** [comment]
ok let's keep the thread going in the [Discussion section](https://github.com/ZOTTCE/fivem-wasm/discussions) instead.
